#!/bin/bash

get_script_folder() {
  relative_path=$(dirname $0)
  # requires python, but supports both mac and linux
  abs_path=$(python -c 'import os,sys ; print(os.path.realpath(sys.argv[1]))' $relative_path)
  echo ${abs_path}
}


project_root=$(get_script_folder)
pushd ${project_root}
echo "sourcing"
source ${project_root}/mawsouq-dev/bin/activate
${project_root}/start-selenium

python ${project_root}/scrape_haraj.py

${project_root}/stop-sel

result=$?
echo "result value -> ${result}"

if [ result = 0 ]
then
    exit 0
else
    exit $result
fi